CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(255) NOT NULL DEFAULT 'USER', verification_code VARCHAR(255),
    verification_expires_at TIMESTAMP(6), password_reset_code VARCHAR(255),
    password_reset_expires_at TIMESTAMP(6), auth_token VARCHAR(255)
);
CREATE TABLE wallet_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, balance NUMERIC(12,2) NOT NULL DEFAULT 0,
    card_limit NUMERIC(12,2) NOT NULL DEFAULT 0, owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, icon VARCHAR(255), color VARCHAR(255), type VARCHAR(255) NOT NULL,
    monthly_limit NUMERIC(12,2) NOT NULL DEFAULT 0, owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE debt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, creditor VARCHAR(255), total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0, total_installments INTEGER NOT NULL DEFAULT 1,
    monthly_payment NUMERIC(12,2) NOT NULL DEFAULT 0, next_due_date DATE, status VARCHAR(255),
    account_id BIGINT REFERENCES wallet_account(id), owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, icon VARCHAR(255), deadline DATE,
    target_amount NUMERIC(12,2) NOT NULL DEFAULT 0, current_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE investment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, investment_type VARCHAR(255), amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    profitability_percent NUMERIC(7,2) NOT NULL DEFAULT 0,
    account_id BIGINT REFERENCES wallet_account(id), owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE finance_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, amount NUMERIC(12,2) NOT NULL,
    date DATE NOT NULL, due_date DATE, received_at DATE, payment_method VARCHAR(255), notes VARCHAR(255),
    reimbursable BOOLEAN NOT NULL DEFAULT FALSE, reimbursement_company VARCHAR(255), reimbursement_email VARCHAR(255),
    receipt_file_name VARCHAR(255), receipt_original_name VARCHAR(255), receipt_content_type VARCHAR(255),
    reimbursement_status VARCHAR(255) NOT NULL DEFAULT 'NOT_REIMBURSABLE',
    reimbursement_sent_at DATE, reimbursement_received_at DATE, status VARCHAR(255) NOT NULL,
    category_id BIGINT REFERENCES category(id), account_id BIGINT REFERENCES wallet_account(id),
    owner_id BIGINT REFERENCES app_user(id)
);
CREATE TABLE auth_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(80) NOT NULL UNIQUE, user_id BIGINT NOT NULL REFERENCES app_user(id),
    created_at TIMESTAMP(6) NOT NULL, expires_at TIMESTAMP(6) NOT NULL
);
